In [1]:
from ipynb.fs.defs.person import Person
from ipynb.fs.full.my_functions import *
import numpy as np
import pandas as pd
from skimage import data, io, segmentation, color, data
from skimage.transform import resize
from skimage.future import graph
import os
import matplotlib.pyplot as plt
import re

In [2]:
classification_file_directory, classification_file_names = file_name_list("Classification_files")
image_dictionary = create_image_dictionary(classification_file_directory, classification_file_names)
people_list = vectorise_images(classification_file_names, image_dictionary, classification_file_directory)

In [3]:
people_list[0].gender = "Male"
people_list[0].race = "Caucasian"

people_list[1].gender = "Male"
people_list[1].race = "Caucasian"

people_list[2].gender = "Male"
people_list[2].race = "Caucasian"

people_list[3].gender = "Male"
people_list[3].race = "Not Caucasian"

people_list[4].gender = "Male"
people_list[4].race = "Caucasian"


people_list[5].gender = "Male"
people_list[5].race = "Caucasian"

people_list[6].gender = "Female"
people_list[6].race = "Caucasian"

people_list[7].gender = "Female"
people_list[7].race = "Caucasian"

people_list[8].gender = "Female"
people_list[8].race = "Caucasian"

people_list[9].gender = "Male"
people_list[9].race = "Not Caucasian"

people_list[10].gender = "Male"
people_list[10].race = "Not Caucasian"

people_list[11].gender = "Male"
people_list[11].race = "Not Caucasian"

people_list[12].gender = "Male"
people_list[12].race = "Caucasian"

people_list[13].gender = "Male"
people_list[13].race = "Caucasian"

people_list[14].gender = "Male"
people_list[14].race = "Caucasian"

people_list[15].gender = "Male"
people_list[15].race = "Caucasian"

people_list[16].gender = "Male"
people_list[16].race = "Caucasian"

people_list[17].gender = "Male"
people_list[17].race = "Caucasian"

people_list[18].gender = "Male"
people_list[18].race = "Caucasian"

people_list[19].gender = "Female"
people_list[19].race = "Caucasian"

for i in people_list:
    if i.race == "Caucasian" and i.gender == "Male":
        i.target = 0
    elif i.race == "Caucasian" and i.gender == "Female":
        i.target = 1
    elif i.race == "Not Caucasian" and i.gender == "Male":
        i.target = 2
    elif i.race == "Not Caucasian" and i.gender == "Female":
        i.target = 3

In [5]:
Categories =["Male Cauc", "Female Cauc", "Male Not Cauc", "Female Not Cauc"]
vector_array = []
target_arr = []
for i in people_list:
    for j in i.list_of_vector_array:
        vector_array.append(j)
        target_arr.append(i.target)

flat_data = np.array(vector_array)
target=np.array(target_arr)

In [6]:
df=pd.DataFrame(flat_data) #dataframe
df['Target']=target
x=df.iloc[:,:-1] #input data
y=df.iloc[:,-1] #output data
display(df)

,0,1,2,3,4,5,6,7,8,9,...,41207,41208,41209,41210,41211,41212,41213,41214,41215,Target
0,0.909804,0.909804,0.909804,0.909804,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,...,0.549020,0.545098,0.545098,0.545098,0.545098,0.529412,0.529412,0.529412,0.529412,0
1,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,...,0.537255,0.533333,0.533333,0.533333,0.533333,0.533333,0.533333,0.533333,0.533333,0
2,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,...,0.576471,0.564706,0.564706,0.564706,0.564706,0.564706,0.564706,0.564706,0.564706,0
3,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,...,0.560784,0.552941,0.552941,0.552941,0.552941,0.556863,0.556863,0.556863,0.556863,0
4,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,0.913725,...,0.584314,0.576471,0.576471,0.576471,0.576471,0.576471,0.576471,0.576471,0.576471,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
570,0.160784,0.160784,0.160784,0.160784,0.149020,0.149020,0.149020,0.149020,0.164706,0.164706,...,0.443137,0.439216,0.439216,0.439216,0.439216,0.439216,0.439216,0.439216,0.439216,1
571,0.156863,0.156863,0.156863,0.156863,0.164706,0.164706,0.164706,0.164706,0.160784,0.160784,...,0.439216,0.443137,0.443137,0.443137,0.443137,0.443137,0.443137,0.443137,0.443137,1
572,0.149020,0.149020,0.149020,0.149020,0.164706,0.164706,0.164706,0.164706,0.164706,0.164706,...,0.439216,0.443137,0.443137,0.443137,0.443137,0.439216,0.439216,0.439216,0.439216,1
573,0.188235,0.188235,0.188235,0.188235,0.188235,0.188235,0.188235,0.188235,0.172549,0.172549,...,0.447059,0.443137,0.443137,0.443137,0.443137,0.447059,0.447059,0.447059,0.447059,1
574,0.054902,0.054902,0.054902,0.054902,0.105882,0.105882,0.105882,0.105882,0.062745,0.062745,...,0.411765,0.337255,0.337255,0.337255,0.337255,0.333333,0.333333,0.333333,0.333333,1

In [7]:
%store x
%store y

Stored 'x' (DataFrame)
Stored 'y' (Series)